### ISSUE TITLE
docker安装后进入后台报错

### ISSUE THREAD

**Issue by YOHN89** [Qsnh/meedu#250]
`The stream or file "/var/www/api/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission deniedThe exception occurred while attempting to log: The stream or file "/var/www/api/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission deniedThe exception occurred while attempting to log: The stream or file "/var/www/api/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission deniedThe exception occurred while attempting to log: App\Meedu\Setting::allConfigTransformedKeyValue|读取AppConfig失败|错误信息:SQLSTATE[42S02]: Base table or view not found: 1146 Table 'meedu.app_config' doesn't exist (SQL: select * from `app_config` order by `sort` asc)Context: {"exception":{}}Context: {"exception":{}}`

<img width="1663" alt="image" src="https://github.com/Qsnh/meedu/assets/109049888/7cdea14d-3277-44b5-a665-6b1cb9c857d7">

**Comment by Qsnh** [comment]
1.安装的宿主机什么操作系统？
2.是否有自行挂载目录？
3.是否是直接 docker compose up -d 安装的？

**Comment by YOHN89** [comment]
> 1.安装的宿主机什么操作系统？ 2.是否有自行挂载目录？ 3.是否是直接 docker compose up -d 安装的？

1, ubuntu server 24.04
2, 未修改过compose.yml配置文件
3, 是的。


另外发现， 同样的操作步骤，在mac 上测试暗转可以正常运行并启动项目进入后台。但是 在ubuntu server上就会失败。 尝试清空镜像、清空文件、重启docker等方法，重新安装还是一样的报错。

**Comment by niuniuland** [comment]
> > 1.安装的宿主机什么操作系统？ 2.是否有自行挂载目录？ 3.是否是直接 docker compose up -d 安装的？
> 
> 1, ubuntu server 24.04 2, 未修改过compose.yml配置文件 3, 是的。
> 
> 另外发现， 同样的操作步骤，在mac 上测试暗转可以正常运行并启动项目进入后台。但是 在ubuntu server上就会失败。 尝试清空镜像、清空文件、重启docker等方法，重新安装还是一样的报错。

同样的问题，Ubuntu 22.04

**Comment by Qsnh** [comment]
我试试看

**Comment by suyuerun** [comment]
我 centos 也会有这个问题, 带佬~ @Qsnh

**Comment by cnjd** [comment]
还没解决吗？Debian12同样的问题

**Comment by beiming-org** [comment]
![image](https://github.com/user-attachments/assets/c2f8bd45-5f29-43a8-b8d8-88ecc90b459a)
同上，我也是一样的问题

**Comment by beiming-org** [comment]
我解决了，按照下面步骤，现进入docker容器内部，按顺序执行：
```
 chown -R www-data:www-data /var/www/api/storage
 chmod -R 775 /var/www/api/storage
 touch /var/www/api/storage/logs/laravel.log
 chown www-data:www-data /var/www/api/storage/logs/laravel.log
chmod 664 /var/www/api/storage/logs/laravel.log
```

**Comment by Qsnh** [comment]
快速修复方法 `docker compose exec meedu chmod 777 storage/logs/laravel.log`

现已经重新构建了 meedu:4.9.11 版本镜像。新版本镜像以修复此问题。之前拉取了4.9.11版本的镜像可以执行先停掉 meedu 镜像（`docker compose down`）然后 `docker system prune -a` 之后重新`docker compose up -d meedu`

**Comment by suyuerun** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qsnh/meedu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月19日(星期一) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qsnh/meedu] docker安装后进入后台报错 (Issue #250)





 
快速修复方法 docker compose exec meedu chmod 777 storage/logs/laravel.log
 
现已经重新构建了 meedu:4.9.11 版本镜像。新版本镜像以修复此问题。之前拉取了4.9.11版本的镜像可以执行先停掉 meedu 镜像（docker compose down）然后 docker system prune -a 之后重新docker compose up -d meedu
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;




好的好的谢谢, 我研究下

**Comment by suyuerun** [comment]
作者大佬, 我按照&nbsp;&nbsp;腾讯云点播 - MeEdu 开源版使用手册 - MeEdu - 杭州白书科技有限公司&nbsp;指导的配置和购买了腾讯云录播, 但是出现了问题, 可以通过后台上传但是不能看到视频文件, 在桶里有, 但是后台看不到下面是截图

**Comment by Qsnh** [comment]
> 作者大佬, 我按照&nbsp;&nbsp;腾讯云点播 - MeEdu 开源版使用手册 - MeEdu - 杭州白书科技有限公司&nbsp;指导的配置和购买了腾讯云录播, 但是出现了问题, 可以通过后台上传但是不能看到视频文件, 在桶里有, 但是后台看不到下面是截图

检查是否给播放域名配置了SSL
